//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAngular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sontestmigDb : DbContext
    {
        public sontestmigDb()
            : base("name=sontestmigConstr")
        {
        }

        public DbSet<Order> Order { get; set; }
        public DbSet<OrderDetail> OrderDetail { get; set; }
        public DbSet<Customer> Customer { get; set; }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
        }
    
    
        //public virtual ObjectResult<User_GetList_Result> User_GetList(Nullable<int> pageIndex, Nullable<int> pageSize)
        //{
        //    var pageIndexParameter = pageIndex.HasValue ?
        //        new ObjectParameter("pageIndex", pageIndex) :
        //        new ObjectParameter("pageIndex", typeof(int));
    
        //    var pageSizeParameter = pageSize.HasValue ?
        //        new ObjectParameter("pageSize", pageSize) :
        //        new ObjectParameter("pageSize", typeof(int));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User_GetList_Result>("User_GetList", pageIndexParameter, pageSizeParameter);
        //}
    }
}
